version: 2

sources:
  - name: tn
    database: tn
    schema: tn
    tables:
      - name: fire_incidents_desnormalized

models:
  - name: stg_fire_incidents
    description: Raw table desnormalized
    columns:
      - name: id
        description: Unique identifier for the incident
      - name: incident_date
        description: Incident date