version: 2

models:
  - name: agg_fire_by_date
    description: Incidents aggregated by date
    columns:
      - name: incident_date
        description: date of the incident
      - name: total_incidents
        description: total incidents registered

  - name: agg_fire_by_battalion
    description: Incidents aggregated by battalion
    columns:
      - name: battalion
        description: Name of the battalion
      - name: total_incidents
        description: Total incidents registered

  - name: agg_fire_by_neighborhood
    description: Incidents aggregated by neighborhood
    columns:
      - name: neighborhood_district
        description: District of the neighborhood
      - name: total_incidents
        description: Total incidents registered

  - name: agg_fire_by_day_and_battalion
    description: Incidents aggregated by day and battalion
    columns:
      - name: incident_date
        description: Date of the incident
      - name: battalion
        description: Name of the battalion