name: fire_case_project
version: '1.0'
config-version: 2

profile: fire_case_project

# Models folder
model-paths: ["models"]

# Folders for tests, docs, etc
test-paths: ["tests"]
analysis-paths: ["analysis"]
data-paths: ["data"]
macro-paths: ["macros"]

# Materialization settings
models:
  fire_case_project:
    +materialized: table
    staging:
      +schema: staging
    marts:
      +schema: marts